---
- hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  roles:
    - role: initial_setup
      tags: setup
    - role: unattended_updates
      tags: setup
    - role: docker
      tags: docker
    - role: wireguard
      tags: wg
