---
- hosts: all
  gather_facts: yes
  vars_files:
    - vars.yml
  roles:
    - role: initial_setup
      tags: initial_setup
    - role: unattended_updates
      tags: unattended_updates
    - role: wireguard
      tags: wireguard
