---
- name: Uninstall old versions
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - podman-docker
    - containerd
    - runc
  become: yes

- name: Update apt and install necessary packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
  become: yes

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker's official GPG key
  shell: 
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
  become: yes

- name: Set permissions for Docker's GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

- name: Set up the Docker repository
  shell: |
    echo "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: yes

- name: Update the apt package index
  apt:
    update_cache: yes
  become: yes

- name: Install Docker Engine, containerd, and Docker Compose
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: yes

- name: Verify Docker installation
  shell: docker run hello-world
  become: yes
