---
- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Python libraries
  pip:
    name: requests
    state: present
  become: yes

- name: Stop and disable host machine WireGuard service
  service:
    name: wg-quick@wg0
    state: stopped
    enabled: no
  become: yes

- name: Allow WireGuard UDP traffic on port 51820
  ufw:
    rule: allow
    port: '51820'
    proto: udp
  become: yes

- name: Allow WireGuard web interface TCP traffic on port 51821
  ufw:
    rule: allow
    port: '51821'
    proto: tcp
  become: yes

- name: Pull and run the wg-easy Docker container
  docker_container:
    name: wg-easy
    image: weejewel/wg-easy
    state: started
    restart_policy: unless-stopped
    env:
      WG_HOST: "{{ inventory_hostname }}"
      PASSWORD: "{{ wg_easy_password }}"
    volumes:
      - "~/.wg-easy:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"
  become: yes
