---
- name: Down wg0
  shell: wg-quick down wg0
  become: yes
  ignore_errors: yes

- name: Up wg0
  shell: wg-quick up wg0
  become: yes

- name: Register clients
  shell: wg set wg0 peer {{ client_public_keys.results[item.index].stdout }} allowed-ips {{ item.ip }}
  become: true
  args:
    executable: /bin/bash
  loop: "{{ clients }}"

- name: Start wireguard on boot
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: yes
  become: yes
